-- Creature identity traits. Generated - do not edit by hand.
--
-- What a hostile nameplate still reveals in 12.1 - level, power type,
-- classification, lieutenant flag, creature family - and which creatures
-- stand together (co). stage: the dungeon segment (bosses killed + 1) the
-- creature is found in. casts: the cast lengths it is known to use.
-- channels: the channel lengths it uses.

CastAheadTraits = {
    [1762] = {
        { npc = 133935, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 1 }, casts = { 3.5 } },
        { npc = 133943, level = 90, power = 1, elite = false, lieutenant = false, family = false, stage = { 1 } },
        { npc = 134157, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 1 } },
        { npc = 134158, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 1 }, casts = { 1, 4 }, channels = { 6 } },
        { npc = 134174, level = 91, power = 0, elite = true, lieutenant = false, family = false, stage = { 1 }, casts = { 2.5, 3.5 } },
        { npc = 134251, level = 90, power = 0, elite = true, lieutenant = false, family = false, stage = { 2 }, co = { 134331 }, casts = { 2.5 } },
        { npc = 134331, level = 91, power = 0, elite = true, lieutenant = false, family = false, stage = { 2 }, co = { 134251 }, casts = { 2.5, 3 }, channels = { 4 } },
        { npc = 134739, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 2 }, casts = { 2 } },
        { npc = 135167, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 3 }, casts = { 2, 3 } },
        { npc = 135192, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 3 }, channels = { 5 } },
        { npc = 135204, level = 90, power = 0, elite = true, lieutenant = false, family = false, stage = { 3 }, casts = { 2.5, 3.5 } },
        { npc = 135231, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 3 }, casts = { 2.5, 5 } },
        { npc = 135239, level = 90, power = 0, elite = true, lieutenant = false, family = false, stage = { 3 } },
        { npc = 135406, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 1 } },
        { npc = 135761, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 3 }, casts = { 8 } },
        { npc = 135764, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 3 }, casts = { 9 } },
        { npc = 135765, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 3 } },
        { npc = 137473, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 2 }, co = { 134251 }, casts = { 2.5 } },
        { npc = 137474, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 2 }, co = { 137478 }, casts = { 2.5, 3 }, channels = { 6 } },
        { npc = 137478, level = 91, power = 0, elite = true, lieutenant = false, family = false, stage = { 2 }, casts = { 2.5 }, channels = { 10 } },
        { npc = 137484, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 2 }, casts = { 2.5 } },
        { npc = 137485, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 2 } },
        { npc = 137486, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 2 }, co = { 137487 }, casts = { 2.5 }, channels = { 2 } },
        { npc = 137487, level = 91, power = 1, elite = true, lieutenant = false, family = true, stage = { 2 }, casts = { 2.5 }, channels = { 5 } },
        { npc = 137969, level = 91, power = 1, elite = true, lieutenant = true, family = false, stage = { 2 }, casts = { 1, 3 }, channels = { 6, 30 } },
        { npc = 137989, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 2 } },
        { npc = 138493, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 4 } },
        { npc = 270502, level = 91, power = 0, elite = true, lieutenant = false, family = false, stage = { 2 }, co = { 137969 }, casts = { 4 } },
        { npc = 273050, level = 91, power = 0, elite = true, lieutenant = false, family = false, stage = { 2 }, casts = { 4 } },
    },
    [1877] = {
        { npc = 134364, level = 90, power = 0, elite = true, lieutenant = false, family = false, stage = { 2 }, casts = { 5 } },
        { npc = 134388, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 2 }, channels = { 20 } },
        { npc = 134389, level = 90, power = 0, elite = true, lieutenant = false, family = false, casts = { 4 } },
        { npc = 134390, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 2 }, casts = { 2.5 } },
        { npc = 134599, level = 90, power = 0, elite = true, lieutenant = false, family = false, stage = { 3 }, casts = { 2, 2.5 } },
        { npc = 134600, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 1, 2 }, channels = { 9 } },
        { npc = 134602, level = 90, power = 3, elite = true, lieutenant = false, family = false, stage = { 1 }, casts = { 2.5 } },
        { npc = 134616, level = 90, power = 1, elite = true, lieutenant = false, family = true, stage = { 1, 2 } },
        { npc = 134629, level = 91, power = 1, elite = true, lieutenant = true, family = false, stage = { 2 }, casts = { 2.5, 4.5 } },
        { npc = 134686, level = 91, power = 1, elite = true, lieutenant = true, family = true, stage = { 2 }, casts = { 3, 4.5 } },
        { npc = 134691, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 3 } },
        { npc = 134990, level = 90, power = 0, elite = true, lieutenant = false, family = false, stage = { 1, 2 }, casts = { 2.5 } },
        { npc = 134991, level = 91, power = 1, elite = true, lieutenant = true, family = false, stage = { 1 }, casts = { 3, 4 } },
        { npc = 135007, level = 91, power = 1, elite = true, lieutenant = true, family = false, stage = { 4 }, casts = { 2.5, 3.5 } },
        { npc = 135562, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 2 } },
        { npc = 135846, level = 90, power = 1, elite = true, lieutenant = false, family = true, stage = { 2 } },
        { npc = 136076, level = 91, power = 0, elite = true, lieutenant = true, family = false, stage = { 3 }, casts = { 1.5, 3 } },
        { npc = 136250, level = 91, power = 0, elite = true, lieutenant = true, family = false, stage = { 4 }, casts = { 2, 4 } },
        { npc = 139110, level = 90, power = 0, elite = true, lieutenant = true, family = false, stage = { 4 } },
        { npc = 139422, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 2 }, casts = { 2.5 } },
        { npc = 139425, level = 90, power = 0, elite = true, lieutenant = false, family = false, stage = { 2 }, casts = { 2.5 } },
        { npc = 268317, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 4 } },
        { npc = 268344, level = 91, power = 1, elite = true, lieutenant = true, family = false, stage = { 4 }, casts = { 2.5 } },
        { npc = 268427, level = 91, power = 0, elite = true, lieutenant = true, family = false, stage = { 4 } },
        { npc = 268491, level = 91, power = 0, elite = true, lieutenant = true, family = false, stage = { 4 }, casts = { 2, 4 } },
        { npc = 268729, level = 90, power = 1, elite = true, lieutenant = false, family = false, stage = { 4 } },
    },
    [2521] = {
        { npc = 187894, level = 90, power = nil, elite = true, lieutenant = nil, family = nil },
        { npc = 187897, level = 91, power = 1, elite = true, lieutenant = nil, family = nil, stage = { 1 }, casts = { 1, 4 }, channels = { 3 } },
        { npc = 187969, level = 90, power = 1, elite = true, lieutenant = nil, family = nil, stage = { 1 } },
        { npc = 188011, level = 90, power = 1, elite = true, lieutenant = nil, family = nil, stage = { 1 } },
        { npc = 188067, level = 90, power = 0, elite = true, lieutenant = nil, family = nil, stage = { 1 }, casts = { 2.5 }, channels = { 15 } },
        { npc = 188244, level = 91, power = 1, elite = true, lieutenant = nil, family = nil, stage = { 1 }, casts = { 2.5, 3.5 }, channels = { 6 } },
        { npc = 189886, level = 91, power = 0, elite = true, lieutenant = nil, family = nil, stage = { 2 }, casts = { 3, 3.5, 5 } },
        { npc = 189893, level = 90, power = nil, elite = true, lieutenant = nil, family = nil },
        { npc = 190034, level = 91, power = 0, elite = true, lieutenant = nil, family = nil, stage = { 2 }, casts = { 1.5, 3.5, 4, 5 } },
        { npc = 190205, level = 90, power = 1, elite = true, lieutenant = nil, family = nil, stage = { 2 } },
        { npc = 190206, level = 90, power = 1, elite = true, lieutenant = nil, family = nil, stage = { 2, 3 }, channels = { 10, 15 } },
        { npc = 190207, level = 90, power = 0, elite = true, lieutenant = nil, family = nil, stage = { 2, 3 }, casts = { 2.5 } },
        { npc = 194622, level = 90, power = nil, elite = true, lieutenant = nil, family = nil },
        { npc = 195119, level = 91, power = 3, elite = true, lieutenant = nil, family = nil, stage = { 2 }, casts = { 2, 2.5 } },
        { npc = 197509, level = 89, power = 0, elite = true, lieutenant = nil, family = nil, stage = { 3 } },
        { npc = 197535, level = 91, power = 0, elite = true, lieutenant = nil, family = nil, stage = { 3 }, casts = { 2 }, channels = { 7 } },
        { npc = 197697, level = 91, power = 1, elite = true, lieutenant = nil, family = nil, stage = { 2 }, casts = { 2.5, 4 }, channels = { 3 } },
        { npc = 197698, level = 91, power = 1, elite = true, lieutenant = nil, family = nil, stage = { 2 }, casts = { 1.5, 2.5, 4 }, channels = { 3 } },
        { npc = 197982, level = 90, power = 1, elite = true, lieutenant = nil, family = nil, stage = { 3 } },
        { npc = 198047, level = 91, power = 0, elite = true, lieutenant = nil, family = nil, stage = { 3 }, casts = { 2, 4 }, channels = { 7 } },
    },
    [2813] = {
        { npc = 235265, level = 91, power = 0, elite = true, lieutenant = true, family = nil, stage = { 3, 4 }, casts = { 1.5, 2 }, channels = { 7 } },
        { npc = 235322, level = 91, power = 1, elite = true, lieutenant = true, family = nil, stage = { 4 }, casts = { 2 }, channels = { 4, 8 } },
        { npc = 235465, level = 91, power = 1, elite = true, lieutenant = false, family = nil, stage = { 3, 4 }, casts = { 1, 4 } },
        { npc = 236071, level = 91, power = 1, elite = true, lieutenant = true, family = nil, stage = { 1 }, casts = { 2, 3 } },
        { npc = 236902, level = 91, power = 0, elite = true, lieutenant = true, family = nil, stage = { 1 }, casts = { 2 }, channels = { 1 } },
        { npc = 236905, level = 91, power = 1, elite = true, lieutenant = true, family = nil, stage = { 3 }, casts = { 2, 2.5 }, channels = { 1.2, 2.5 } },
    },
    [2825] = {
        { npc = 241869, level = 91, power = 1, elite = true, lieutenant = false, family = nil, stage = { 2 }, casts = { 2, 4 } },
        { npc = 244889, level = 91, power = 0, elite = true, lieutenant = nil, family = nil, stage = { 3 }, casts = { 2.5, 3, 4 } },
        { npc = 245146, level = 91, power = 1, elite = true, lieutenant = true, family = nil, stage = { 3 }, casts = { 2, 3 } },
        { npc = 245855, level = 91, power = 1, elite = true, lieutenant = false, family = nil, stage = { 1 }, casts = { 1.5 }, channels = { 5 } },
    },
    [2859] = {
        { npc = 245346, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 1, 2 }, casts = { 2.5, 3 } },
        { npc = 245513, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 4 }, casts = { 2, 3 }, channels = { 6 } },
        { npc = 246871, level = 91, power = 1, elite = true, lieutenant = false, family = false, stage = { 3, 4 }, casts = { 2.5, 3 } },
        { npc = 249756, level = 91, power = 1, elite = true, lieutenant = true, family = true, stage = { 4 }, casts = { 2, 3 } },
        { npc = 254850, level = 91, power = 1, elite = true, lieutenant = true, family = false, stage = { 1, 2, 3, 4 }, casts = { 1.5, 2 }, channels = { 3 } },
    },
    [2923] = {
        { npc = 244260, level = 91, power = 1, elite = true, lieutenant = true, family = nil, stage = { 1 }, channels = { 10 } },
        { npc = 244309, level = 91, power = 1, elite = true, lieutenant = true, family = nil, stage = { 1 }, casts = { 2.5, 3.5 } },
        { npc = 245950, level = 91, power = 1, elite = true, lieutenant = false, family = nil, stage = { 2, 3 }, casts = { 2, 5 }, channels = { 4 } },
        { npc = 252053, level = 91, power = 1, elite = true, lieutenant = false, family = nil, stage = { 1, 2, 3 }, casts = { 2 }, channels = { 6, 30 } },
        { npc = 252072, level = 91, power = 0, elite = true, lieutenant = false, family = nil, stage = { 1, 2, 3 }, casts = { 4 } },
        { npc = 263228, level = 91, power = 1, elite = true, lieutenant = false, family = nil, stage = { 2, 3 }, casts = { 2.5 }, channels = { 6 } },
        { npc = 267545, level = 91, power = 1, elite = true, lieutenant = false, family = nil, stage = { 1 }, casts = { 2, 3, 8 } },
        { npc = 267546, level = 91, power = 0, elite = true, lieutenant = false, family = nil, stage = { 1 }, casts = { 2, 3 }, channels = { 9 } },
        { npc = 268184, level = 91, power = 1, elite = true, lieutenant = false, family = nil, stage = { 3 }, casts = { 2, 4.5, 9 }, channels = { 6 } },
    },
    [2993] = {
        { npc = 261554, level = 91, power = 1, elite = true, lieutenant = nil, family = true, stage = { 1, 3 }, casts = { 3 }, channels = { 5 } },
        { npc = 261557, level = 90, power = 0, elite = true, lieutenant = false, family = nil, stage = { 2, 3 }, casts = { 3 }, channels = { 6 } },
        { npc = 261560, level = 90, power = 1, elite = true, lieutenant = false, family = nil, stage = { 1, 3 }, casts = { 4 } },
        { npc = 261573, level = 91, power = 1, elite = true, lieutenant = nil, family = false, stage = { 3 }, casts = { 2, 3 }, channels = { 5 } },
        { npc = 262011, level = 91, power = 1, elite = true, lieutenant = nil, family = false, stage = { 2 }, casts = { 3 }, channels = { 5 } },
        { npc = 263109, level = 91, power = 0, elite = true, lieutenant = nil, family = false, stage = { 3 }, casts = { 2, 3.5 }, channels = { 9 } },
        { npc = 270306, level = 91, power = 1, elite = true, lieutenant = nil, family = false, stage = { 1, 3 }, casts = { 3 }, channels = { 2 } },
    },
}
