import csv
import glob
import os
import sys

REACTS = ("DEFENSIVE", "DODGE", "DISPEL")
MIN_APPLICATIONS = 3
DAMAGE = ("SPELL_DAMAGE", "SPELL_PERIODIC_DAMAGE")
MAXHP, AMOUNT, OVERKILL, ABSORBED = 15, 31, 33, 37
COLUMNS = ["instance", "zone", "spell", "name", "applications", "keys", "deaths",
           "median_share", "p90_share", "react"]


def fields(line):
    if "  " not in line:
        return None
    return next(csv.reader([line.split("  ", 1)[1].rstrip("\n")]))


def number(f, i):
    try:
        return float(f[i])
    except (IndexError, ValueError):
        return 0.0


def scan(paths):
    stats = {}
    for path in paths:
        instance = zone = None
        key = 0
        in_boss = False
        windows = {}
        with open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                f = fields(line)
                if not f:
                    continue
                event = f[0]
                if event == "CHALLENGE_MODE_START":
                    zone, instance = f[1], int(f[2])
                    key += 1
                    windows.clear()
                    in_boss = False
                elif event == "CHALLENGE_MODE_END":
                    instance = None
                    windows.clear()
                elif instance is None:
                    continue
                elif event == "ENCOUNTER_START":
                    in_boss = True
                elif event == "ENCOUNTER_END":
                    in_boss = False
                elif event == "SPELL_AURA_APPLIED":
                    if in_boss or len(f) < 13 or f[12] != "DEBUFF":
                        continue
                    if not f[1].startswith("Creature-") or not f[5].startswith("Player-"):
                        continue
                    spell = int(f[9])
                    row = stats.setdefault((instance, spell), {
                        "zone": zone, "name": f[10], "applications": 0, "keys": set(),
                        "deaths": 0, "shares": []})
                    row["applications"] += 1
                    row["keys"].add((path, key))
                    windows[(f[5], spell)] = {"row": row, "share": 0.0}
                elif event == "SPELL_AURA_REMOVED":
                    window = windows.pop((f[5], int(f[9])), None) if len(f) > 9 else None
                    if window:
                        window["row"]["shares"].append(window["share"])
                elif event in DAMAGE:
                    if not f[1].startswith("Creature-"):
                        continue
                    maxhp = number(f, MAXHP)
                    if maxhp <= 0:
                        continue
                    share = (number(f, AMOUNT) - max(0.0, number(f, OVERKILL)) + number(f, ABSORBED)) / maxhp
                    for (dst, _), window in windows.items():
                        if dst == f[5]:
                            window["share"] += share
                elif event == "UNIT_DIED" and f[5].startswith("Player-"):
                    for k in [k for k in windows if k[0] == f[5]]:
                        window = windows.pop(k)
                        window["row"]["deaths"] += 1
                        window["row"]["shares"].append(0.0)
    for row in stats.values():
        row["keys"] = len(row["keys"])
    return stats


def percentile(values, q):
    s = sorted(values)
    return s[min(len(s) - 1, int(q * len(s)))] if s else 0.0


def read_reacts(path):
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))
    return {(int(r["instance"]), int(r["spell"])): r["react"] for r in rows if r.get("react")}


def write_review(stats, path):
    reacts = read_reacts(path)
    rows = [(k, v) for k, v in stats.items() if v["applications"] >= MIN_APPLICATIONS]
    rows.sort(key=lambda kv: (kv[0][0], -kv[1]["deaths"], -percentile(kv[1]["shares"], 0.5)))
    with open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write("\t".join(COLUMNS) + "\n")
        for (instance, spell), v in rows:
            fh.write("\t".join([str(instance), v["zone"], str(spell), v["name"], str(v["applications"]),
                                str(v["keys"]), str(v["deaths"]), "%.2f" % percentile(v["shares"], 0.5),
                                "%.2f" % percentile(v["shares"], 0.9), reacts.get((instance, spell), "")]) + "\n")


def gen(review_path, out_path):
    with open(review_path, encoding="utf-8") as fh:
        rows = [r for r in csv.DictReader(fh, delimiter="\t") if r.get("react")]
    by_instance = {}
    for r in rows:
        if r["react"] not in REACTS:
            raise ValueError("unknown react %r for spell %s" % (r["react"], r["spell"]))
        by_instance.setdefault(int(r["instance"]), []).append(r)
    out = ["-- Generated by tools/debuffs.py from the reviewed debuff list. Do not edit by hand.",
           "CastAheadDebuffs = {"]
    for instance in sorted(by_instance):
        group = by_instance[instance]
        out.append("    [%d] = { -- %s" % (instance, group[0]["zone"].replace('"', "'")))
        for r in sorted(group, key=lambda r: int(r["spell"])):
            out.append('        [%d] = "%s", -- %s' % (int(r["spell"]), r["react"], r["name"].replace('"', "'")))
        out.append("    },")
    out.append("}")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")


if __name__ == "__main__":
    if len(sys.argv) == 4 and sys.argv[1] == "scan":
        write_review(scan(sorted(glob.glob(sys.argv[2]))), sys.argv[3])
    elif len(sys.argv) == 4 and sys.argv[1] == "gen":
        gen(sys.argv[2], sys.argv[3])
    else:
        sys.exit("usage: debuffs.py scan <log glob> <review.tsv> | gen <review.tsv> <Debuffs.lua>")
