"""Pull enemy facts out of Mythic Dungeon Tools.

The combat logs know timing - how long a cast takes, how often it repeats - but
nothing about what a mob is. MDT knows exactly that: which spells belong to which
creature, which of them can be interrupted, and which creatures are bosses. Its
data files are plain Lua tables, so a targeted scan is enough; keying everything
by npcID means no dungeon-name mapping is needed.

Usage: mdt.py "<AddOns>/MythicDungeonTools" mdt.json [Packs.lua]

With a third argument, the same scan also writes Packs.lua for the addon: per
dungeon, how many of each creature exist at all (every clone MDT places) and
which creatures stand together in each pack (MDT's group number). The runtime
counts deaths against the totals and narrows by pack composition; both are
regenerated whenever MDT updates.
"""
import sys, os, re, json, glob

ENEMY = re.compile(r'\n  \[\d+\] = \{\n(.*?)(?=\n  \[\d+\] = \{|\n\};|\Z)', re.S)
NAME = re.compile(r'\["name"\]\s*=\s*"([^"]*)"')
NPC_ID = re.compile(r'\["id"\]\s*=\s*(\d+)')
IS_BOSS = re.compile(r'\["isBoss"\]\s*=\s*true')
# The creatures a boss mod actually covers carry an encounter id as well.
# "isBoss" alone also marks the mini-bosses and rares standing in the
# trash path - Flamegullet, Defier Draghar, High Channeler Ryvati - which
# nothing else announces and which our own logs show casting outside any
# ENCOUNTER_START window.
ENCOUNTER = re.compile(r'\["encounterID"\]\s*=\s*(\d+)')
LEVEL = re.compile(r'\["level"\]\s*=\s*(\d+)')
SPELLS = re.compile(r'\["spells"\]\s*=\s*\{(.*?)\n    \},', re.S)
SPELL = re.compile(r'\[(\d+)\] = \{(.*?)\},', re.S)
ENGLISH_NAME = re.compile(r'englishName\s*=\s*"([^"]*)"')
CLONES = re.compile(r'\["clones"\]\s*=\s*\{(.*?)\n    \},', re.S)
GROUP = re.compile(r'\["g"\]\s*=\s*(\d+)')


def parse(path, packs=None):
    text = open(path, encoding="utf-8", errors="replace").read()
    # Only the enemy table; the file also holds map POIs shaped similarly.
    start = text.find("MDT.dungeonEnemies")
    if start < 0:
        return {}
    english = ENGLISH_NAME.search(text[:start])
    dungeon = packs.setdefault(english.group(1), {"total": {}, "packs": {}}) \
        if packs is not None and english else None
    out = {}
    for block in ENEMY.finditer(text[start:]):
        body = block.group(1)
        npc_id = NPC_ID.search(body)
        name = NAME.search(body)
        if not npc_id or not name:
            continue
        spells = {}
        spell_block = SPELLS.search(body)
        if spell_block:
            for spell in SPELL.finditer(spell_block.group(1)):
                spells[int(spell.group(1))] = "interruptible" in spell.group(2)
        level = LEVEL.search(body)
        if dungeon is not None and not IS_BOSS.search(body):
            npc = int(npc_id.group(1))
            clones = CLONES.search(body)
            groups = GROUP.findall(clones.group(1)) if clones else []
            # A clone without a group stands alone; it still counts.
            placed = len(re.findall(r'\["x"\]', clones.group(1))) if clones else 0
            dungeon["total"][npc] = dungeon["total"].get(npc, 0) + max(placed, len(groups))
            for g in groups:
                pack = dungeon["packs"].setdefault(int(g), {})
                pack[npc] = pack.get(npc, 0) + 1
        out[int(npc_id.group(1))] = {
            "mob": name.group(1),
            "boss": bool(IS_BOSS.search(body)),
            "encounter": int(ENCOUNTER.search(body).group(1)) if ENCOUNTER.search(body) else None,
            # UnitLevel is one of the few things still readable off a hostile
            # nameplate, so it can narrow candidates before any cast happens.
            "level": int(level.group(1)) if level else None,
            "spells": spells,
        }
    return out


def write_packs(packs, path):
    """CastAheadPacks[dungeon name] = { total = { [npc] = n }, packs = { { [npc] = n }, ... } }.

    Keyed by MDT's English name; Core maps it through CastAheadData's own
    `name`, so no instance-id table has to be kept in step with MDT.
    """
    out = open(path, "w", encoding="utf-8", newline="\n")
    out.write("-- Generated by tools/mdt.py from Mythic Dungeon Tools. Do not edit.\n")
    out.write("-- total: creatures of each kind placed in the dungeon. packs: who stands\n")
    out.write("-- together, one entry per group, with how many of each.\n")
    out.write("CastAheadPacks = {\n")
    for name in sorted(packs):
        d = packs[name]
        if not d["total"]:
            continue
        out.write('    ["%s"] = {\n' % name.replace('"', "'"))
        out.write("        total = { %s },\n" % ", ".join(
            "[%d] = %d" % (npc, n) for npc, n in sorted(d["total"].items())))
        out.write("        packs = {\n")
        for g in sorted(d["packs"]):
            out.write("            { %s },\n" % ", ".join(
                "[%d] = %d" % (npc, n) for npc, n in sorted(d["packs"][g].items())))
        out.write("        },\n    },\n")
    out.write("}\n")
    out.close()


def main(mdt_dir, out_path, packs_path=None):
    merged = {}
    packs = {} if packs_path else None
    files = []
    for sub in ("*/*.lua", "*.lua"):
        files.extend(glob.glob(os.path.join(mdt_dir, sub)))
    for path in sorted(set(files)):
        for npc_id, row in parse(path, packs).items():
            existing = merged.get(npc_id)
            # A creature can appear in several dungeons; merge what is known.
            if existing:
                existing["boss"] = existing["boss"] or row["boss"]
                existing["encounter"] = existing["encounter"] or row["encounter"]
                existing["level"] = existing["level"] or row["level"]
                existing["spells"].update(row["spells"])
            else:
                merged[npc_id] = row

    json.dump({str(k): v for k, v in merged.items()},
              open(out_path, "w", encoding="utf-8"), ensure_ascii=False)
    bosses = sum(1 for r in merged.values() if r["encounter"])
    kickable = sum(1 for r in merged.values() for ok in r["spells"].values() if ok)
    spells = sum(len(r["spells"]) for r in merged.values())
    print("%d creatures (%d bosses), %d spells (%d interruptible) -> %s"
          % (len(merged), bosses, spells, kickable, out_path))
    if packs_path:
        write_packs(packs, packs_path)
        print("%d dungeons with pack data -> %s"
              % (sum(1 for d in packs.values() if d["total"]), packs_path))


if __name__ == "__main__":
    main(*sys.argv[1:])
